server:
  port: 9090

spring:
  main:
    time-zone: Europe/Istanbul
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_PROLYZE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
  mail:
    host: smtp.gmail.com
    port: 587
    username: prolyzeai@gmail.com
    password: ${PROLYZE_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
prolyze:
  issuer: ${PROLYZE_ISSUER}
  secret-key: ${PROLYZE_SECRET_KEY}