server:
  port: 9090

spring:
  main:
    time-zone: Europe/Istanbul
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_PROLYZE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
